// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9MWqZ61xKdBIOB1RXpFszfkNmIfc4V88',
    appId: '1:747929764724:web:7d48c1a78f905a0a73e221',
    messagingSenderId: '747929764724',
    projectId: 'moviebooking-cb614',
    authDomain: 'moviebooking-cb614.firebaseapp.com',
    storageBucket: 'moviebooking-cb614.firebasestorage.app',
    measurementId: 'G-QR39P4JSRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ65Y9hNUTOj_GIvTxlcWm3C9xiXal-QQ',
    appId: '1:747929764724:android:c0b8aca7633305aa73e221',
    messagingSenderId: '747929764724',
    projectId: 'moviebooking-cb614',
    storageBucket: 'moviebooking-cb614.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAieiJTagd5ph2CdU7lc0S-KzvH7IclMMw',
    appId: '1:747929764724:ios:302095445e0c3cc173e221',
    messagingSenderId: '747929764724',
    projectId: 'moviebooking-cb614',
    storageBucket: 'moviebooking-cb614.firebasestorage.app',
    iosBundleId: 'com.example.bookfilim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAieiJTagd5ph2CdU7lc0S-KzvH7IclMMw',
    appId: '1:747929764724:ios:302095445e0c3cc173e221',
    messagingSenderId: '747929764724',
    projectId: 'moviebooking-cb614',
    storageBucket: 'moviebooking-cb614.firebasestorage.app',
    iosBundleId: 'com.example.bookfilim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9MWqZ61xKdBIOB1RXpFszfkNmIfc4V88',
    appId: '1:747929764724:web:e8d0cd75122181c773e221',
    messagingSenderId: '747929764724',
    projectId: 'moviebooking-cb614',
    authDomain: 'moviebooking-cb614.firebaseapp.com',
    storageBucket: 'moviebooking-cb614.firebasestorage.app',
    measurementId: 'G-GMJLJF5HYV',
  );
}
